### ISSUE TITLE
关于ewt后台看课检测通过率问题

### ISSUE THREAD

**Issue by Anya-TY** [SudoSuBash/EWT-Killer-Box#10]
## 你是否在汇报一个bug(是/否)?
否
## 插件程序版本
R2408B-2024.07.24
## 提供程序运行的截图
无需
## 在浏览器按F12，然后将"控制台"的输出信息粘贴到此处
无需
## 在此提供描述
已给star 感谢作者大大 脚本刷课 填选择题等功能制作非常好 但在这里想询问作者大大是否能够研究一下看课通过检测率的机制 目前使用该脚本刷课看课检测通过率会提示NULL显示为( - ) 谢谢作者大大 我承诺会合理使用

- [√] 我已经看过readme.md,并且确定这个浏览器/扩展对此插件是兼容的<br>
- [√] 我已经查询过没有与这篇issue的主题类似的issue

**Comment by SudoSuBash** [comment]
已经知晓。请问你是从哪儿获取的通过检测率呢？

**Comment by SudoSuBash** [comment]
新功能已经在 R2409B-2024.07.25 中添加。

**Comment by Anya-TY** [comment]
抱歉没有即使看到 图片已发出
![1722000309235](https://github.com/user-attachments/assets/17c51ceb-c838-4cff-8352-ae70aa9bfee0)
