### ISSUE TITLE
⚠插件被EWT反制⚠

### ISSUE THREAD

**Issue by CodeSmallPanda** [SudoSuBash/EWT-Killer-Box#11]
## 你是否在汇报一个bug(是/否)?
否
## 插件程序版本
R2410B-2024.07.26

## 运行环境
windows

#### 浏览器类型(e.g.Chrome):
Edge

#### 用的扩展类型(e.g.Tampermonkey):
Tampermonkey

#### 手机还是电脑:
电脑

## 提供程序运行的截图
![image](https://github.com/user-attachments/assets/ba442b99-a601-43fc-8fa3-785124e226dd)

## 在浏览器按F12，然后将"控制台"的输出信息粘贴到此处
已清除控制台
bundle.fd20d233.js?fd20d23387c305e87127:46 socurcrtype--- 1
bundle.fd20d233.js?fd20d23387c305e87127:46 第一次进入--

## 在此提供描述
使用插件刷新界面时有概率（80%）触发EWT反制，反制期间所有形成的数据无效

- [√ ] 我已经看过readme.md,并且确定这个浏览器/扩展对此插件是兼容的<br>
- [√ ] 我已经查询过没有与这篇issue的主题类似的issue

**Comment by SudoSuBash** [comment]
此bug在2410版本中已经修复。

**Comment by SudoSuBash** [comment]
R2410 版本中不会出现这个提示。
Ewt 检测原理是检测.w-mask元素是否存在，但是在r2410中，我已经将wmask元素的class更改。
检查你的版本号，并且更新。

**Comment by CodeSmallPanda** [comment]
> R2410 版本中不会出现这个提示。 Ewt 检测原理是检测.w-mask元素是否存在，但是在r2410中，我已经将wmask元素的class更改。 检查你的版本号，并且更新。

解决了，感谢作者
