### ISSUE TITLE
ewt刷课功能只能完成部分进度

### ISSUE THREAD

**Issue by qq1256** [SudoSuBash/EWT-Killer-Box#12]
## 你是否在汇报一个bug(是/否)?
是
## 插件程序版本
R2410B-2024.07.26
## 提供程序运行的截图
![image](https://github.com/user-attachments/assets/7346c29c-fa33-4f8b-99c4-589870c99cfc)

## 在浏览器按F12，然后将"控制台"的输出信息粘贴到此处
[Message] id为144584041的用户跳课成功,课程信息为{"lessonid":84586,"courseid":18468,"homeworkid":10302028,"coursetag":"课程讲","subjectName":"英语","ratio":0.23049255583126552}
userscript.html?name=EWT-ewt-e%25E7%25BD%2591%25E9%2580%259A-%25E5%2588%25B7%25E8%25AF%25BE%252B%25E8%2587%25AA%25E5%258A%25A8%25E5%25AE%258C%25E6%2588%2590%25E9%2580%2589%25E6%258B%25A9%25E9%25A2%2598%25E7%259A%2584%25E5%25B7%25A5%25E5%2585%25B7%25E7%25AE%25B1.user.js&id=714f2276-7cf7-4e92-87f1-45f5ea45bdc6:2010 [Message] 日志上传成功.
bundle.fd20d233.js?fd20d23387c305e87127:46 显示----
## 在此提供描述
只能完成部分课程观看进度

- [√ ] 我已经看过readme.md,并且确定这个浏览器/扩展对此插件是兼容的<br>
- [√ ] 我已经查询过没有与这篇issue的主题类似的issue

**Comment by BestAdrian** [comment]
同样问题

**Comment by SudoSuBash** [comment]
该问题系ewt漏洞修复所致。
现已经在查找相对应的解决方法

**Comment by mzjmnq** [comment]
这个部分进度对应到时间大约是75秒，我试过很多次了，所有课都是每次跳课只能产生75秒的有效进度

**Comment by hhntoa** [comment]
目前进度一点都不能刷了 全为0%
