### ISSUE TITLE
刷课时不会增加看课时长

### ISSUE THREAD

**Issue by hhntoa** [SudoSuBash/EWT-Killer-Box#14]
## 你是否在汇报一个bug(是/否)?
   是

## 插件程序版本

    R2410B-2024.07.26

#### 浏览器类型(e.g.Chrome):
MoZilla FireFox
#### 用的扩展类型(e.g.Tampermonkey):
Tampermonkey
#### 手机还是电脑:
电脑

## 提供程序运行的截图 
无

## 在浏览器按F12，然后将"控制台"的输出信息粘贴到此处 
目前无法跳课

## 在此提供描述
另一个ISSUE中已提出目前无法刷课的问题
报告另一个问题: 在之前能刷课时刷完之后在后台查看看课时长基本为0(刷课时不会增加看课时长)
希望作者在修复另一个问题时一并修复这个问题
谢谢！！

- [√] 我已经看过readme.md,并且确定这个浏览器/扩展对此插件是兼容的<br>
- [√] 我已经查询过没有与这篇issue的主题类似的issue

**Comment by laoshuikaixue** [comment]
根据资料 在去年ewt方面就已经修复了clog备用上传接口bug 只可刷进度，时长将不被记录 此issue应该是无效的 新版本可能会采用其他方法

**Comment by SudoSuBash** [comment]
> 根据资料 在去年ewt方面就已经修复了clog备用上传接口bug 只可刷进度，时长将不被记录 此issue应该是无效的 新版本可能会采用之前的接口

正如这位反馈者所说，以后版本将会采用挂课的方式。

**Comment by qq1256** [comment]
![image](https://github.com/user-attachments/assets/0ca02da3-0483-440b-99d3-6ca907b312b3)
![image](https://github.com/user-attachments/assets/f530dfca-452e-4e16-853d-87ae4ef72184)
ma貌似又被ewt反制了，但是刷课可以正常增加一小部分进度
