### ISSUE TITLE
显示了对于第三方软件的警告

### ISSUE THREAD

**Issue by IXccdesu** [SudoSuBash/EWT-Killer-Box#15]
## 你是否在汇报一个bug(是/否)?
是
## 插件程序版本
R2410B-2024.07.26
#### 手机还是电脑:
电脑
## 提供程序运行的截图
![屏幕截图 2024-07-26 180913](https://github.com/user-attachments/assets/0aeb8eb4-0317-4fbe-9978-e6ce7ca9e4a8)

## 在此提供描述
在开启插件的情况下，页面显示了以下警告【您好，为保障用户数据安全，平台禁止使用一切未知来源的软件或插件辅助学习。由第三方软件产生的学习结果将被标记为非正常的学习行为，产生的学习数据不纳入统计，属无效数据。请务必遵守平台规则，避免因数据无效导致相关学习任务未完成，感谢您的理解和支持。】
同时刷课功能不可用

- [x] 我已经看过readme.md,并且确定这个浏览器/扩展对此插件是兼容的<br>
- [x] 我已经查询过没有与这篇issue的主题类似的issue

**Comment by hhntoa** [comment]
看之前的issue
更新插件版本
