### ISSUE TITLE
非重复 第三方软件检测

### ISSUE THREAD

**Issue by Anya-TY** [SudoSuBash/EWT-Killer-Box#16]
## 你是否在汇报一个bug(是/否)?
否
## 插件程序版本
R2410B-2024.07.26
## 提供程序运行的截图
无需
## 在浏览器按F12，然后将"控制台"的输出信息粘贴到此处
无需
## 在此提供描述
![image](https://github.com/user-attachments/assets/5392adc3-58ef-42ed-bbdf-b16c60c63b2e)
如图所示 我确认使用的为R2410B-2024.07.26版本 但依旧会提示第三方 经过测试 判定机制依旧为读取.w-xxxxx 将当前版本的两处w-有种来抓我呀 修改为其他任意内容后 提示即可消失
附上个issues #10的后台图片 希望能够帮助到你
![image](https://github.com/user-attachments/assets/9b856559-6835-4cbb-981a-ba75604a7feb)

- [√] 我已经看过readme.md,并且确定这个浏览器/扩展对此插件是兼容的<br>
- [√] 我已经查询过没有与这篇issue的主题类似的issue

**Comment by SudoSuBash** [comment]
昨天晚上就看到了。
这是他们的检测源码。
在今天的新版本中，会发布挂课功能更新和新一轮避检。![Image_1722037945496.png](https://github.com/user-attachments/assets/1ff055ea-93ce-45cf-a42c-fb00f10c1438)

![Image_1722037947580.png](https://github.com/user-attachments/assets/6b23271c-b852-4593-b400-88c51f51967a)
