### ISSUE TITLE
更新到2R-Final后插件再次被ewt检测

### ISSUE THREAD

**Issue by NEK0NEO** [SudoSuBash/EWT-Killer-Box#17]
## 你是否在汇报一个bug(是/否)?
否
## 插件程序版本
2R-Final
#### 浏览器类型(e.g.Chrome):
狐猴浏览器
#### 用的扩展类型(e.g.Tampermonkey):
Tampermonkey
#### 手机还是电脑:
手机
## 提供程序运行的截图
![Screenshot_20240729_160535_com lemurbrowser exts](https://github.com/user-attachments/assets/d0d752a3-c244-4075-91e4-5756a4a95347)

## 在浏览器按F12，然后将"控制台"的输出信息粘贴到此处
无
## 在此提供描述
插件再次被ewt检测，但课程进度目前能正常上传

- [√] 我已经看过readme.md,并且确定这个浏览器/扩展对此插件是兼容的<br>
- [√] 我已经查询过没有与这篇issue的主题类似的issue

**Comment by laoshuikaixue** [comment]
因为2R-Final改回了w-mask 检测不影响使用
