### ISSUE TITLE
无法挂课

### ISSUE THREAD

**Issue by CandyZhiNai** [SudoSuBash/EWT-Killer-Box#18]
## 你是否在汇报一个bug(是/否)?
是
## 插件程序版本
2R-Final
## 提供程序运行的截图
![QQ_1722257419484](https://github.com/user-attachments/assets/872b02c9-c698-4123-9c2a-fd23f373c3ad)

## 在此提供描述
刷新过多次页面 换过账号   手机使用火狐浏览器同样显示此报错

- [√ ] 我已经看过readme.md,并且确定这个浏览器/扩展对此插件是兼容的<br>
- [ √] 我已经查询过没有与这篇issue的主题类似的issue

**Comment by SudoSuBash** [comment]
将FinishCourseSignatureUtil类改成下图代码即可解决问题
油猴我是不会再改了，此处更改也是我对于b版的最后一次更新，要不然估计要出事情了
![f04511d52f28279b22f13808da642a88](https://github.com/user-attachments/assets/8d05bc8a-bff1-4a58-885f-4e843e0160dc)
